# version: "3.7"

# services:
#     sample:
#         container_name: solar
#         build:
#             context: .
#             dockerfile: Dockerfile
#         volumes:
#             - ".:/app"
#             - "/app/node_modules"
#         ports:
#             - 9040:3000
#         environment:
#             - CHOKIDAR_USEPOLLING=true
################################################
# version: "3.8"

# services:
#     app:
#         container_name: solar
#         image: solar
#         build:
#             context: .
#             dockerfile: Dockerfile
#         ports:
#             - 9040:3000
#         environment:
#             - CHOKIDAR_USEPOLLING=true

version: "3.7"

services:
    hello-world:
        container_name: hello-world
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 9050:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
