version: "3.7"

services:
    sample:
        container_name: solar
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 9040:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
